export const TYPES = { 
    App: Symbol.for("App"),
    Logger: Symbol.for("Logger"),
    DataSourceConnect: Symbol.for("DataSourceConnect"),
    Repository: Symbol.for("Repository"),
    UserService: Symbol.for("UserService"),
    StudentService: Symbol.for("StudentService"),
    RoleService: Symbol.for("RoleService"),
    CourseService: Symbol.for("CourseService"),
    CourseClassService: Symbol.for("CourseClassService"),
    CourseClassStudentService: Symbol.for("CourseClassStudentService"),
    DepartmentService: Symbol.for("DepartmentService"),
    RouteHelper: Symbol.for("RouteHelper"),
    ClassStudentService: Symbol.for("ClassStudentService"),
};